variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    env: dev
    cluster: cloudkube-dev-m59i-cluster
    resourceGroup: cloudkube-dev-m59i-rg
    hostname: architecture-review.dev.cloudkube.io
    url: https://architecture-review.dev.cloudkube.io/
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    env: staging
    cluster: cloudkube-staging-1bp-cluster
    resourceGroup: cloudkube-staging-1bp-rg
    hostname: architecture-review.staging.cloudkube.io
    url: https://architecture-review.staging.cloudkube.io/

jobs:
- job: SetupVariables
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - script: |
      git_sha=$(git rev-parse --short HEAD)
      echo "##vso[task.setvariable variable=gitSha]$git_sha"
      echo "##vso[task.setvariable variable=dockerTag]$(env)-$git_sha"
    displayName: 'Resolve Variables'
  - script: |
      echo "Environment: $(env)"
      echo "Cluster: $(cluster)"
      echo "Resource Group: $(resourceGroup)"
      echo "Hostname: $(hostname)"
      echo "URL: $(url)"
      echo "Docker Tag: $(dockerTag)"
    displayName: 'Echo Configurations'
