trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: azureServiceConnection
    value: 'Azure service connection name' # Define this in your Azure DevOps environment or pipeline settings

jobs:
- job: KubectlApply
  displayName: 'Apply Kubernetes Configurations'
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))

  steps:
  - checkout: self

  - task: AzureCLI@2
    displayName: 'Login to Azure'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
        az aks get-credentials --name $(clusterName) --resource-group $(resourceGroup) --overwrite-existing

  - script: |
      echo "Configuring Kubectl and Kustomize"
      KUBECONFIG=$(Agent.TempDirectory)/kubeconfig
      export KUBECONFIG
      kubectl version --client -o yaml
      kustomize build $(overlays) | envsubst | kubectl apply -f -
    displayName: 'kubectl apply (DEV or STAGING)'
    env:
      APP_BUILD_SHA: $(gitSha)
      IMAGE_TAG: $(imageTag)
      INGRESS_HOSTNAME: $(hostname)

  - script: |
      echo "Logging out from Kubernetes"
      rm $KUBECONFIG
    displayName: 'Cleanup Kubernetes Config'
